### ISSUE TITLE
GUI closes when pressing 1, or 2...

### ISSUE THREAD

**Issue by kinow** [simonarvin/eyeloop#10]
Hi,

Found it via reddit. I read a lot of ebooks, comics, etc, on my laptop. And when I am on my extra-lazy mode, I feel bothered when I have to uncross my arms to move to the next page. So I have always been thinking how hard it would be to track my eyes and move the pages automatically for me.

There might be some existing plugin for these e-readers, but I wanted to build my own, and `eyeloop` appears to have some of what I need, at least in the engine part.

Alas I couldn't get it to work after quickly reading the docs and some of the code, although it's almost bed time here :bed: 

I found the tooltip window (it was hidden on my second monitor, almost out of sight, only its toolbar showing) and then pressed `2`, and the GUI closed with an error (I think) message. Tried clicking on another tab, then pressing W, D, E, etc, nothing. The other tab had `1` to press. Tried that, it closed again with

```
module 'cv2.cv2' has no attribute 'TrackerMedianFlow_create'
Try again: Hover and click on the pupil, then press 1.
'Shape' object has no attribute 'source'
Importer released.

```

So just wondering; do I have to create an experiment to get it working? I thought I would be able to first see the engine in action. Even though I want to learn how the engine works, I may try some experiments too, e.g. could be something like reading something I know is really boring, or one of the books I procrastinate to read, and compare with some interesting book. Or read in different languages, and see if there's any difference.

Though being just a programmer I may be thinking how to use eyeloop in a wrong way :-)

Thanks again for sharing. Found it on reddit and got interested after I saw the OP replying some interesting comments there :+1: Well done!

Bruno

**Comment by simonarvin** [comment]
Dear Bruno

Experiments are not required. I'm on shift at the hospital at the moment, but will make sure to address your post in detail when I am available. I apologize for any inconveniences, EyeLoop is still very much beta.

Thank you for showing interest and getting involved!

Best,
Simon Arvin

**Comment by kinow** [comment]
Thanks Simon! No apologies necessary. EyeLoop is super interesting and I feel like I can learn w lot (and have fun) using it.

Thank you!

**Comment by simonarvin** [comment]
Dear Bruno

Very interesting ideas! I reckon there might be a difference in eye behaviour when procrastinating versus when attentive, which could be very exciting to investigate.

Regarding the crash: I added a temporary fix that should prevent EyeLoop from crashing when selecting the pupil or corneal reflections. Let me know how it goes. I moved all example footage to [repo eyeloop_playground](https://github.com/simonarvin/eyeloop_playground/tree/master/examples) (aimed at providing examples and teaching materials).

The current GUI is very barebones and not user-friendly. I will look into developing an alternative, perhaps based on Qt or Tkinter (if you have any recommendations, please tell :) ). I aimed to make the GUI modular to enable users to integrate EyeLoop in their own experiment managers, eg designed for visual experiments, two-photon microscopy etc. - however, it is certainly best to provide a proper GUI as a default option

Best,
Simon

**Comment by kinow** [comment]
Hi Simon,

>Very interesting ideas! I reckon there might be a difference in eye behaviour when procrastinating versus when attentive, which could be very exciting to investigate.

Great! I have a lot of boring books I have been avoiding to read. Maybe running this experiment would help me get rid of some of these books in my todo pile.

>Regarding the crash: I added a temporary fix that should prevent EyeLoop from crashing when selecting the pupil or corneal reflections. Let me know how it goes. I moved all example footage to repo eyeloop_playground (aimed at providing examples and teaching materials).

Great! I'll test it again today.

>The current GUI is very barebones and not user-friendly. I will look into developing an alternative, perhaps based on Qt or Tkinter (if you have any recommendations, please tell :) ). I aimed to make the GUI modular to enable users to integrate EyeLoop in their own experiment managers, eg designed for visual experiments, two-photon microscopy etc. - however, it is certainly best to provide a proper GUI as a default option

I used Qt on Krita and QGIS. I am no expert, but their API documentation was quite comprehensive, and I managed to make the changes I needed. Its learning curve is probably steeper than Tk (and maybe more than GTK as well).

I've been working mainly on web now. But if I had to pick one for desktop, it would probably be Qt.

**Comment by simonarvin** [comment]
Thank you Bruno!

**Comment by kinow** [comment]
Tested today, and it didn't crash again! :tada: I might need to read the rest of the docs, and learn how to calibrate or configure it correctly. Or perhaps my camera is not good enough, as it didn't quite focus on my eye. Will take another look another day. Thanks!

![image](https://user-images.githubusercontent.com/304786/87400197-9af6e380-c60c-11ea-992f-647c904e2256.png)
