### ISSUE TITLE
improve blink detection

### ISSUE THREAD

**Issue by simonarvin** [simonarvin/eyeloop#12]
## Background ##
EyeLoop detects blinking by monitoring changes in the monochromatic spectrum (= changes in the mean brightness of the frame). 

It turns out that blinks produce very distinct patterns in the mean value when viewed over time, which can be used to detect blinking. **How to threshold this pattern depends on the species monitored (eg human, mice) and the general properties of the image (eg contrasts).** Thus, we have to normalise this function to improve detection across species and footage types.

### Get started ###
`check_blink()` is found in _/eyeloop/engine/engine.py_. For human and mice test footage, [click here](https://github.com/simonarvin/eyeloop_playground/tree/master/examples).

Best,
Simon

**Comment by tosimplicity** [comment]
It would be even amazing if we can detect intentional blinks (vs involuntary eye blinks).

**Comment by simonarvin** [comment]
see #24
