### ISSUE TITLE
seamless near-to-far eye-tracking

### ISSUE THREAD

**Issue by simonarvin** [simonarvin/eyeloop#19]
# Eye-tracking both at a distance, and in close-ups #
EyeLoop's current eye-tracking algorithm works well in close-up footage. However, some users might want to use EyeLoop at a distance. Thus, we should consider implementing eye-tracking that works at a distance as well. Perhaps, it is best to implement a dedicated algorithm for distant eye-tracking. Then, we could fall back on distant eye-tracking whenever the close-up algorithm fails. Making this fall-back seamless is a priority, and should preferably be bidirectional (ie switching both from near to distant, and distant to near).

Instead of rewriting this code, we could consider integrating Antoine Lame's open-source repository: https://github.com/antoinelame/GazeTracking

Best,
Simon

**Comment by kinow** [comment]
I think the use cases I had in mind match this description. +1 (and will have a look at the linked repository)
