### ISSUE TITLE
Oflfine tracking limited to 15-16FPS, any way to improve it?

### ISSUE THREAD

**Issue by catubc** [simonarvin/eyeloop#33]
Hi
We are starting to use your tracker, and are finding that 15-16FPS is the fastest that it processes our videos (acquired at 30-90Fps).  Here's an image of running eyeloop for a previously recorded .avi.

https://drive.google.com/file/d/1UrOGWEx92dEnImPnksNqxVUA9gKDin0N/view?usp=sharing

We were thinking about digging into your algorithms to speed them up, but I assume you guys know better than us how to do this.

Any advice for this? 

For closed loop (online) tracking this would generally not be enough. 

Thanks so much,
catubc

**Comment by simonarvin** [comment]
Hi Cat, perhaps you haven't initiated tracking (you're still left in a slowed-down stream for selecting the pupil and/or corneal reflections). 

After selecting the pupil, (press <kbd>z</kbd>, then <kbd>y</kbd>). This initiates tracking at full speed.

**Comment by catubc** [comment]
Yes, you right, sorry didn't see the info in the docs. I see it now.
