### ISSUE TITLE
Hardware recommendations

### ISSUE THREAD

**Issue by iandol** [simonarvin/eyeloop#35]
Hi, do you have recommended camera hardware, or a list of options. Your readme says >1000Hz on non-specialised hardware, but most standard camera do not approach this frame rate, so I assume you mean the processing rate *if* a camera could feed in images fast enough. openEyeTrack use a Genie Nano M640 NIR and IR illuminator that can go up to 800fps, I assume this could be used?

How does your system handle calibration (for human and/or non-human primate subjects)?

**Comment by simonarvin** [comment]
Hi @iandol,
Your assumption is correct: The 1000 Hz is assuming that frames are fed to EyeLoop fast enough, e.g., from an offline recording or fast camera feed. Unfortunately, I have no recommendations for hardware. The Genie camera should be compatible with EyeLoop, if you can retrieve the camera frames through Python, e.g., using OpenCV.

EyeLoop does not provide calibration. It could be implemented through an Extractor module

Best,
Simon

**Comment by iandol** [comment]
Thanks Simon. Do you plan to add calibration in the future, as this is fairly core feature for eye tracking?

**Comment by simonarvin** [comment]
This is not yet in our plans for the near future, however I can look into implementing it. The calibration step converts the eye tracking data to monitor pixel coordinates, correct? Such to reveal where the eye is looking
