### ISSUE TITLE
How can I get the circle with my vedio?

### ISSUE THREAD

**Issue by Myzhencai** [simonarvin/eyeloop#36]
Hi ,thanks for the fantastatic work ,I do need the module to get the pupil circle and the point of IR illumination ，but I have no idea how to make it work like showed .Could you please help me?

![image](https://user-images.githubusercontent.com/21084423/115681701-59f3e280-a387-11eb-9954-d51b27d801a1.png)

**Comment by simonarvin** [comment]
Hi!

Your tracking parameters are likely off. Try adjusting them. See [this link](https://github.com/simonarvin/eyeloop/tree/master/eyeloop/guis/minimum).


## Getting started ##
- **A**: Select the corneal reflections by hovering and key-pressing <kbd>2</kbd>, <kbd>3</kbd> or <kbd>4</kbd>. This initiates the tracking algorithm, which is rendered in the preview panel. Adjust binarization (key-press <kbd>W</kbd>/<kbd>S</kbd>) and gaussian (key-press <kbd>E</kbd>/<kbd>D</kbd>) parameters to improve detection. To switch between corneal reflections, key-press the corresponding index (for example, key-press <kbd>2</kbd> to modify corneal reflection "2").
- **B**: Select the pupil by hovering and key-pressing <kbd>1</kbd>. Similar to the corneal reflections, this initiates tracking. Adjust binarization (key-press <kbd>R</kbd>/<kbd>F</kbd>) and gaussian parameters (key-press <kbd>T</kbd>/<kbd>G</kbd>) for optimal detection. 
- **C**: To initiate the eye-tracking trial, key-press <kbd>Z</kbd> and confirm by key-pressing <kbd>Y</kbd>.
