### ISSUE TITLE
eyeloop.guis.minimum.minimum_gui - INFO - cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by catubc** [simonarvin/eyeloop#37]
Hello

We have previously tested the eyeloop utility and it seemed to work ok. But now it doesn't seem to run on a basic .mp4 video we have.

We get the above error.

Any advice!?

Thanks so much,

![eyeloop](https://user-images.githubusercontent.com/4267452/128866723-39e945b1-b8ca-4764-8b81-db861ebd9c33.png)

**Comment by simonarvin** [comment]
Hi catubc

Sorry for the late reply, things have been quite hectic lately.

Seems like EyeLoop fails to detect the pupil (thus returning a _NoneType_ object). Have you tried adjusting the binarization parameters using the R/F keys? From the binary window (right window in your screencap), I think this is the problem

Best,
Simon

**Comment by catubc** [comment]
Yes, we did try many options. We tinkered with the GUI for quite a while, but it did not seem to work.
